spring:
  application:
    name: auth-server


server:
  servlet:
    context-path: /auth
  port: 7777

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:epxing@${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.security: debug
